/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Tycho Magnetic Anomaly (https://sketchfab.com/Tycho_Magnetic_Anomaly)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/lenticular-morie-d5327b1e3f1c40f780089eadda1c13a8
title: Lenticular Morié
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/scene.gltf')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="Sphere_0" rotation={[-Math.PI, 0, -Math.PI]} scale={[-1, 0, -1]}>
                <mesh name="Object_4" geometry={nodes.Object_4.geometry} material={materials['Material.001']} />
              </group>
              <group name="Sphere001_1" rotation={[-Math.PI, 0, -Math.PI]} scale={[-1, 0, -1]}>
                <mesh name="Object_6" geometry={nodes.Object_6.geometry} material={materials['Material.001']} />
              </group>
              <group name="Sphere002_2" rotation={[-Math.PI, 0, -Math.PI]} scale={[-1, 0, -1]}>
                <mesh name="Object_8" geometry={nodes.Object_8.geometry} material={materials['Material.001']} />
              </group>
              <group name="Sphere003_3" rotation={[-Math.PI, 0, -Math.PI]} scale={[-1, 0, -1]}>
                <mesh name="Object_10" geometry={nodes.Object_10.geometry} material={materials['Material.001']} />
              </group>
              <group name="Sphere004_4" rotation={[-Math.PI, 0, -Math.PI]} scale={[-1, 0, -1]}>
                <mesh name="Object_12" geometry={nodes.Object_12.geometry} material={materials['Material.001']} />
              </group>
              <group name="Sphere005_5" rotation={[-Math.PI, 0, -Math.PI]} scale={[-1, 0, -1]}>
                <mesh name="Object_14" geometry={nodes.Object_14.geometry} material={materials['Material.001']} />
              </group>
              <group name="Sphere006_6" rotation={[-Math.PI, 0, -Math.PI]} scale={[-1, 0, -1]}>
                <mesh name="Object_16" geometry={nodes.Object_16.geometry} material={materials['Material.001']} />
              </group>
              <group name="Sphere007_7" rotation={[-Math.PI, 0, -Math.PI]} scale={[-1, 0, -1]}>
                <mesh name="Object_18" geometry={nodes.Object_18.geometry} material={materials['Material.001']} />
              </group>
              <group name="Sphere008_9" rotation={[-Math.PI, 0, -Math.PI]} scale={[-1, 0, -1]}>
                <mesh name="Object_20" geometry={nodes.Object_20.geometry} material={materials['Material.001']} />
              </group>
              <group name="Sphere009_10" rotation={[-Math.PI, 0, -Math.PI]} scale={[-1, 0, -1]}>
                <mesh name="Object_22" geometry={nodes.Object_22.geometry} material={materials['Material.001']} />
              </group>
              <group name="Sphere010_11" rotation={[-Math.PI, 0, -Math.PI]} scale={[-1, 0, -1]}>
                <mesh name="Object_24" geometry={nodes.Object_24.geometry} material={materials['Material.001']} />
              </group>
              <group name="Sphere011_12" rotation={[-Math.PI, 0, -Math.PI]} scale={[-1, 0, -1]}>
                <mesh name="Object_26" geometry={nodes.Object_26.geometry} material={materials['Material.001']} />
              </group>
              <group name="Sphere012_13" rotation={[-Math.PI, 0, -Math.PI]} scale={[-1, 0, -1]}>
                <mesh name="Object_28" geometry={nodes.Object_28.geometry} material={materials['Material.001']} />
              </group>
              <group name="Sphere013_14" rotation={[-Math.PI, 0, -Math.PI]} scale={[-1, 0, -1]}>
                <mesh name="Object_30" geometry={nodes.Object_30.geometry} material={materials['Material.001']} />
              </group>
              <group name="Sphere014_15" rotation={[-Math.PI, 0, -Math.PI]} scale={[-1, 0, -1]}>
                <mesh name="Object_32" geometry={nodes.Object_32.geometry} material={materials['Material.001']} />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
